# Generated by Django 3.2.5 on 2022-04-29 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0007_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('Twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('Youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('Linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('Website', models.CharField(blank=True, max_length=255, null=True)),
                ('Podcast', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
